Added/modified tests, made some small changes in the code
hussalen/assignment_3 pull request #35
Opened 2024-12-25 16:01 UTC by madhtl

2024-12-25 16:45 UTC, hussalen requested changes
Tests that were replaced still fail :(

2024-12-25 16:58 UTC, madhtl commented
Which ones for example? I only see the AssignmentTests in my segment failing-these are Shanto's

2024-12-25 17:10 UTC, hussalen commented
wait, which ones are yours? Because I see e.g. "Subject_ShouldAllowMultipleTimeslots" failing @madhtl

2024-12-25 17:16 UTC, madhtl commented
<img width="529" alt="Zrzut ekranu 2024-12-25 o 18 15 31" src="https://github.com/user-attachments/assets/960d9c42-8030-4552-befb-a3f0e128120c" />
Why isn't it failing at mines

2024-12-25 17:39 UTC, hussalen commented
wait let me grab your branch and check

2024-12-25 18:17 UTC, hussalen commented
I see the same issue, tests pass on my IDE but fail with dotnet test. I suspect this is because your IDE and my IDE runs tests in a "sandboxed" environment, whereas `dotnet test` runs holistically, so issues like "A Timeslot with Schedule ID 1 already exists" are bound to happen, because there are many places in the code where a timeslot object is initialized with ID 1. 

![image](https://github.com/user-attachments/assets/72d66923-916a-4506-b87f-6b51e04d11ae)

@madhtl So let's treat `dotnet test` as the source of truth, even if it passes in your IDE.. BTW, the ids of the timeslot objects should be automatically generated just like every other object.

2024-12-25 18:25 UTC, hussalen commented
so yeah while the tests look alright, the underlying logic of some of the classes with the tests are sort of flawed

2024-12-25 18:37 UTC, madhtl commented
Okok will try to fix it

2025-01-02 17:23 UTC, hussalen commented on project/Timeslot.cs
> +            if (_exam != null && value != null && _exam != Defaults.DEFAULT_EXAM && _exam != value)
This check basically means that the EditExam method will never work. I don't think this makes much sense.

2025-01-02 17:29 UTC, hussalen commented on project/Timeslot.cs
> +        if (_exam != null && _exam != exam)
```suggestion
        if (_exam != Defaults.DEFAULT_EXAM)
```

This is the best way, since technically our default objects are our "null" values..

2025-01-02 17:31 UTC, hussalen commented on project/Timeslot.cs
> +        if (_exam != null)
Clearing the exam means you just propagate the _exam field with the Defaults.DEFAULT_EXAM object.

2025-01-02 17:32 UTC, hussalen commented
@madhtl IMO fix the issues above then let me know

2025-01-02 20:37 UTC, madhtl commented
So I think for now the ClearExam is unnecessary, before EditExam() it turns out the AddExam() is not working properly, especially if we want to keep the 1-1 relation so in Exam constructor we need timeslot. anddd well I wrote some comments, pls have a look, maybe you have an idea for this

2025-01-03 15:46 UTC, hussalen commented on project/Timeslot.cs
> +        if (_exam != Defaults.DEFAULT_EXAM && _exam != exam)
So we can only add an exam if the passed value is the same as the object field _exam? Doesn't make sense. It should be _exam != Defaults.DEFAULT_EXAM && _exam == exam or simply just _exam != Defaults.DEFAULT_EXAM

2025-01-03 15:49 UTC, hussalen commented
> So I think for now the ClearExam is unnecessary, before EditExam() it turns out the AddExam() is not working properly, especially if we want to keep the 1-1 relation so in Exam constructor we need timeslot. anddd well I wrote some comments, pls have a look, maybe you have an idea for this

In a 1-1 relation, we do it in the same vain as any relationship that has "1" in it. We set the value to default if the object is no longer needed. Imagine only being able to continuously add exams to timeslots and vice-versa.. That doesn't make sense at all, as sometimes objects need to be removed even if the relation is 1-1, 1..*-1, etc.. @madhtl

2025-01-03 15:51 UTC, hussalen commented on project/Timeslot.cs
> +    { //regarding the Timeslot_AddExam_ShouldAssignExamCorrectly() test I guess it cannot pass bc it has timeslot already assigned
Then why not just update the unit test to reflect it, rather than updating the functionality to tailor to the unit test? @madhtl

2025-01-03 16:00 UTC, hussalen commented on project/Timeslot.cs
> +            if (_exam != Defaults.DEFAULT_EXAM && value != Defaults.DEFAULT_EXAM)
You basically did not address this: 
https://github.com/hussalen/assignment_3/pull/35/commits/647c2089a8d7ef6a4411a91f85376859597939cd#diff-42486c39e46d3b1f140f4735d80e5a556a597e36e747b5ce11370afdbe4c4fc0R112
but rather added more boilerplate code here. Also, UpdateExam will never work because of this. It's better to remove all of this actually since we do the checking on those methods anyway, so all of this is completely redundant.

2025-01-03 16:05 UTC, hussalen commented on project/Timeslot.cs
> +    public Timeslot(int scheduleId, DateTime date, TimeSpan startTime, TimeSpan endTime, bool isDummy = false)
Why `bool isDummy`.. We know that Default objects are public and static, so you can just check objects against the default...

2025-01-03 17:20 UTC, madhtl commented on project/Timeslot.cs
> +        if (_exam != Defaults.DEFAULT_EXAM && _exam != exam)
No we can add it when (first cons.) the previous value was default and our current value is not, the second-when the previous exam is not default-to prevent overwriting and the third allow adding changing the exam from some value to a default one

2025-01-08 16:37 UTC, hussalen approved these changes
Looks good for now

2025-01-08 16:38 UTC, merged